name: "Bin Collector Addon - Simbio"
version: "2.0"
slug: "bin_collector"
description: "A Go application to fetch waste collection data"
startup: "application"
boot: "auto"
init: false
options:
  address: "zaƒçret 69"
schema:
  address: str
ports:
  8081/tcp: 8081
